---
- name: Initialize the directory
  hosts: localhost
  gather_facts: no

  tasks:

    - name: Clone SNO deployment playbook
      git:
        repo: https://github.com/empovit/openshift-on-equinix-with-gpu.git
        dest: openshift-playbook
        version: main
        single_branch: yes

    - name: Pull Riva Helm chart
      debug:
        msg: "TODO: Pull Riva Helm chart from NGC"