---
- name: Initialize the directory
  hosts: localhost
  gather_facts: no

  tasks:

    - name: Clone GPU-on-OpenShift playbook
      git:
        repo: https://github.com/empovit/openshift-on-equinix-with-gpu.git
        dest: openshift-playbook
        version: main
        single_branch: yes

    - name: Install OpenShift playbook requirements
      command: ansible-galaxy install -r openshift-playbook/requirements.yml
      register: _install_requirements
      changed_when: "'Nothing to do' not in _install_requirements.stdout"

    - name: Pull Riva Helm chart
      debug:
        msg: "TODO: Pull Riva Helm chart from NGC"