---
- name: Deploy an SNO cluster
  import_playbook: openshift-playbook/sno.yml
  vars:
    temp_directory: "{{ playbook_dir }}/tmp"

- name: Deploy Riva on the SNO cluster
  hosts: localhost
  gather_facts: no
  roles:
    - riva_server
