- name: Deploy Riva API server
  kubernetes.core.helm:
    name: riva-api
    chart_ref: riva-api
    namespace: riva
    create_namespace: true
    kubeconfig: "{{ kubeconfig }}"
    state: present
    values:
      ngcCredentials:
        password: "{{ ngc_api_key }}"
        email: "{{ ngc_email }}"
      modelRepoGenerator:
        modelDeployKey: "{{ 'tlt_encode' | b64encode }}"
        modelDeployVolume: ""
        artifactDeployVolume: ""
      service:
        type: NodePort