- name: Update entries in /etc/hosts
  ansible.builtin.replace:
    path: /etc/hosts
    regexp: "([0-9\\.]+)(\\s+[a-z0-9\\-\\.]+{{ cluster_name }}.redhat.com)"
    replace: "{{ new_api_vip }}\\2"
    backup: yes
    owner: root
    group: root
    mode: '0644'
  become: true
  when: old_api_vip != new_api_vip

- name: Add entries to /etc/hosts
  ansible.builtin.lineinfile:
    path: /etc/hosts
    line: |

      {{ new_api_vip }}	api.{{ cluster_name }}.redhat.com
      {{ new_api_vip }}	oauth-openshift.apps.{{ cluster_name }}.redhat.com
      {{ new_api_vip }}	console-openshift-console.apps.{{ cluster_name }}.redhat.com
      {{ new_api_vip }}	grafana-openshift-monitoring.apps.{{ cluster_name }}.redhat.com
      {{ new_api_vip }}	thanos-querier-openshift-monitoring.apps.{{ cluster_name }}.redhat.com
      {{ new_api_vip }}	prometheus-k8s-openshift-monitoring.apps.{{ cluster_name }}.redhat.com
      {{ new_api_vip }}	alertmanager-main-openshift-monitoring.apps.{{ cluster_name }}.redhat.com
    backup: yes
    owner: root
    group: root
    mode: '0644'
  become: true
  when: not old_api_vip and new_api_vip not in lookup('file', '/etc/hosts')

- name: Warn if the IP already in /etc/host for another cluster
  ansible.builtin.debug:
    msg: "Address {{ new_api_vip }} is already associated with another cluster in /etc/hosts. Update the file manually"
  when: new_api_vip not in lookup('file', '/etc/hosts')